name: tektoncd-operator
components:
  - name: index-4.19
    dockerfile: .konflux/olm-catalog/index/v4.19/Dockerfile.catalog
    nudges: [ "" ]
tekton:
  watched-sources: ( ".konflux/olm-catalog/index/***".pathChanged())
