name: tektoncd-operator
components:
  - name: index-4.15
    dockerfile: .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
    nudges: [ "" ]
tekton:
  watched-sources: ( ".konflux/olm-catalog/index/***".pathChanged())
