name: tektoncd-operator
upstream: tektoncd/operator
components:
  - name: operator
  - name: webhook
  - name: proxy
  - name: bundle
    dockerfile: .konflux/olm-catalog/bundle/Dockerfile
    nudges:
      - operator-{{hyphenize .Version.Version}}-index-4-18
    tekton:
      watched-sources: (".konflux/patches/***".pathChanged() || ".konflux/olm-catalog/bundle/***".pathChanged())
github:
  update-sources: |
    - name: fetch-payload
      run: |
        pushd upstream
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        popd

        if [[ "$BRANCH_NAME" != "main" ]] && [[ -z $(git status --porcelain --untracked-files=no) ]]; then
          echo "No change, do nothing"
          # exit 0
        fi
        # Operator SDK
        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.37.0/operator-sdk_linux_amd64
        curl -LO ${OPERATOR_SDK_DL_URL}
        chmod +x operator-sdk_linux_amd64 && sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk

        operator-sdk version

        # Python with requirements (yaml here)
        # We could migrate to go...
        python3 -m venv sync-sources
        source sync-sources/bin/activate
        pip3 install -r requirements.txt

        # Update operator's payload and stuff
        make update-payload-and-reference
        pushd upstream
        rm -fR cmd/openshift/operator/kodata operatorhub
        git checkout HEAD .
        popd

